spring:
  jpa:
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.dentalcore: INFO
    org.springframework: WARN

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

server:
  forward-headers-strategy: framework
