/**
 * Catalog registry — discovers every translation file automatically.
 *
 * Wave-2 agents: you do NOT edit this file. Drop your JSON catalogs at
 *   src/i18n/locales/en/<namespace>.json
 *   src/i18n/locales/es/<namespace>.json
 * (one namespace per feature dir, e.g. `patients`, `billing`) and they are
 * picked up by the glob below at build time. See ./GUIDE.md.
 */

type Catalog = Record<string, unknown>;

const modules = import.meta.glob('./locales/*/*.json', {
  eager: true,
  import: 'default',
}) as Record<string, Catalog>;

export const resources: Record<string, Record<string, Catalog>> = {};
const namespaceSet = new Set<string>();

for (const [path, catalog] of Object.entries(modules)) {
  const match = /\.\/locales\/([^/]+)\/([^/]+)\.json$/.exec(path);
  if (!match) continue;
  const [, language, namespace] = match;
  (resources[language] ??= {})[namespace] = catalog;
  namespaceSet.add(namespace);
}

export const namespaces: string[] = [...namespaceSet].sort();
